version: '3'

services:
  django:
    build:
      context: ./backend
    ports:
      - "8000:8000"
  react:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/react

